version: '3.7'

services:
  web:
    build: .
    command: >
        sh -c "python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server
  celery:
    build: .
    command: celery -A task_scheduler worker -B -E -l info
    volumes:
      - ./:/app/
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - CELERY_TIMEZONE=Europe/Berlin
    depends_on:
      - db
      - redis
      - web
  celery-beat:
    build: .
    command: celery -A task_scheduler beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./:/app/
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - CELERY_TIMEZONE=Europe/Berlin
    depends_on:
      - db
      - redis
      - web
  db:
    image: postgres:12.4-alpine
    environment:
        - POSTGRES_PASSWORD=postgres
        - PGTZ=CEST
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata: